### ISSUE TITLE
Async Values

### ISSUE THREAD

**Issue by calvinmetcalf** [tmcw/mistakes#13]
It would be nice to get values from async functions into the right hand side, off the top of my I  can't think of a simple way to do this, but I can think of an overly complicated way which is to have a which takes line and content and puts content onto line, which would then be in the scope of each lines eval bound to the current line, i.e.e:

``` JavaScript
____printToRight(line,content){
  do(stuff);
};
...
eval("var printToRight ="+____printToRight.bind(null,lineNo)+";"+____js);
```

**Comment by tmcw** [comment]
Hmm, yeah - can't think of a clean way to implement this - the contract of mistakes as been that the values on the right are 'the value of the line as executed, right now' - so, for instance, for loops print the result, rather than each iteration.

Re: not tricky - I'd like to stay away from code-rewriting because it tends to miss js's complexity at certain points (lots of ways to make and call functions, etc).

I think there might be a way to pull this off in userspace with an enhanced console pattern that does async-friendly console.log.

**Comment by calvinmetcalf** [comment]
This is one of those things promises would help with.

**Comment by tmcw** [comment]
> This is one of those things promises would help with.

I'm not sure how, can you explain further?

**Comment by calvinmetcalf** [comment]
A promise is a syncronized response to an async function so if code returned a promise then the right hand side could have pending or something until the promises was fulfilled or rejected and then replace the value with the value returned by the promise. 

I meant that in a somewhat wistful tone.

**Comment by tmcw** [comment]
I'm seeing a path for promises here - basically detect whether a value has a `.then` and bind on that.

**Comment by tmcw** [comment]
On second thought, promises seem like an odd way to do this, and I just don't see them being well-supported everywhere unless they're truly language-level. Going a different route here.

**Comment by calvinmetcalf** [comment]
They are language level, chrome and firefox support them without flags
